### ISSUE TITLE
Terminal integration

### ISSUE THREAD

**Issue by Brinfer** [yttrion/doomnvim#3]
**Describe the bug**
The reopening is not necessarily done on the last file (penultimate folder/workspace).

**To Reproduce**
1. Open a folder
2. Select a file
3. Quit Vim
4. Reopen Vim
The error frequency is quite random.

**Expected behavior**
Reopen on the last workspace/file. Otherwise an empty workspace

**Desktop (please complete the following information):**
 - OS: Manjaro (Kernel Linux 5.8.16)
 - Console: Konsole (Version 20.08.1)

**Comment by yttrion** [comment]
This is due to vim-workspace. Its config  file does not specify `g:workspace_autocreate = 1` which automatically creates a session file

I'm currently working on it in the **dev** branch
